package dev.lysmux.web4.core;

public enum ErrorCode {
    VALIDATION_ERROR,

    INVALID_CREDENTIALS,
    AUTH_PROVIDER_ERROR,

    USER_NOT_FOUND,
    USER_ALREADY_CONFIRMED,
    USER_PENDING_CONFIRMATION,
    USER_BLOCKED,
    USER_DELETED,
    USER_USERNAME_EXISTS,
    USER_EMAIL_EXISTS,

    TOKEN_INVALID,
    NO_AUTHENTICATED,
    FORBIDDEN,
}
